import { contextBridge, ipcRenderer } from 'electron';
import type { DesktopAPI } from '../shared/types';
import type { TaskState } from '../shared/chat';
const api: DesktopAPI = {
  snapshot:() => ipcRenderer.invoke('workspace:snapshot'),
  chooseProject:() => ipcRenderer.invoke('project:choose'),
  addProject:path => ipcRenderer.invoke('project:add',path),
  removeProject:id => ipcRenderer.invoke('project:remove',id),
  createSession:input => ipcRenderer.invoke('session:create',input),
  updateSession:input => ipcRenderer.invoke('session:update',input),
  saveDraft:(id,text) => ipcRenderer.invoke('session:draft',{id,text}),
  savePanelDrafts:(id,patch) => ipcRenderer.invoke('session:panel-drafts',{id,patch}),
  setSelection:id => ipcRenderer.invoke('session:select',id),
  deleteSession:id => ipcRenderer.invoke('session:delete',id),
  chatSnapshot:id => ipcRenderer.invoke('chat:snapshot',id),
  chatPage:(id,options) => ipcRenderer.invoke('chat:page',{id,...options}),
  searchChat:(id,query,before) => ipcRenderer.invoke('chat:search',{id,query,before}),
  chatAttention:() => ipcRenderer.invoke('chat:attention'),
  sendChat:(id,text,attachments) => ipcRenderer.invoke('chat:send',{id,text,attachments}),
  respondChat:(id,requestId,decision) => ipcRenderer.invoke('chat:respond',{id,requestId,decision}),
  pickAttachments:id => ipcRenderer.invoke('files:pick',id),
  listAttachments:id => ipcRenderer.invoke('files:attachments',id),
  removeAttachment:(id,path) => ipcRenderer.invoke('files:remove-attachment',{id,path}),
  queryHistory:(projectId,options) => ipcRenderer.invoke('history:query',{projectId,...options}),
  gitChanges:id => ipcRenderer.invoke('git:changes',id),
  gitDiff:(id,path,staged) => ipcRenderer.invoke('git:diff',{id,path,staged}),
  listProjectFiles:(id,query) => ipcRenderer.invoke('files:list',{id,query}),
  readProjectFile:(id,path) => ipcRenderer.invoke('files:read',{id,path}),
  worktreeInfo:id => ipcRenderer.invoke('worktree:info',id),
  mergeWorktree:id => ipcRenderer.invoke('worktree:merge',id),
  cleanupWorktree:id => ipcRenderer.invoke('worktree:cleanup',id),
  diagnostics:sessionId => ipcRenderer.invoke('cli:diagnostics',sessionId),
  workflows:sessionId => ipcRenderer.invoke('workflow:list',sessionId),
  createWorkflow:input => ipcRenderer.invoke('workflow:create',input),
  startWorkflow:id => ipcRenderer.invoke('workflow:start',id),
  continueWorkflow:id => ipcRenderer.invoke('workflow:continue',id),
  retryWorkflow:id => ipcRenderer.invoke('workflow:retry',id),
  cancelWorkflow:id => ipcRenderer.invoke('workflow:cancel',id),
  deleteWorkflow:id => ipcRenderer.invoke('workflow:delete',id),
  exportWorkflow:id => ipcRenderer.invoke('workflow:export',id),
  reviseWorkflowStage:(id,stageId,instruction) => ipcRenderer.invoke('workflow:revise',{id,stageId,instruction}),
  onWorkflows:callback => { const listener = () => callback(); ipcRenderer.on('workflow:changed',listener); return () => ipcRenderer.removeListener('workflow:changed',listener); },
  onChat:callback => { const listener = (_event:Electron.IpcRendererEvent,id:string,state?:TaskState) => callback(id,state); ipcRenderer.on('chat:changed',listener); return () => ipcRenderer.removeListener('chat:changed',listener); },
  startSession:id => ipcRenderer.invoke('session:start',id),
  stopSession:id => ipcRenderer.invoke('session:stop',id),
  interruptSession:id => ipcRenderer.invoke('session:interrupt',id),
  terminalSnapshot:id => ipcRenderer.invoke('terminal:snapshot',id),
  writeTerminal:(id,data) => ipcRenderer.invoke('terminal:write',{id,data}),
  resizeTerminal:(id,cols,rows) => ipcRenderer.invoke('terminal:resize',{id,cols,rows}),
  saveSettings:settings => ipcRenderer.invoke('settings:save',settings),
  detect:() => ipcRenderer.invoke('cli:detect'),
  history:projectId => ipcRenderer.invoke('history:list',projectId),
  gitInfo:sessionId => ipcRenderer.invoke('git:info',sessionId),
  exportTranscript:id => ipcRenderer.invoke('session:export',id),
  openFolder:id => ipcRenderer.invoke('folder:open',id),
  onState:callback => { const listener = (_event:Electron.IpcRendererEvent,data:Parameters<typeof callback>[0]) => callback(data);ipcRenderer.on('workspace:state',listener);return () => ipcRenderer.removeListener('workspace:state',listener); },
  onError:callback => { const listener=(_event:Electron.IpcRendererEvent,message:string)=>callback(message);ipcRenderer.on('workspace:error',listener);return()=>ipcRenderer.removeListener('workspace:error',listener); },
  onNavigate:callback => { const listener=(_event:Electron.IpcRendererEvent,id:string)=>callback(id);ipcRenderer.on('session:navigate',listener);return()=>ipcRenderer.removeListener('session:navigate',listener); },
  onCapabilities:callback => {const listener=(_event:Electron.IpcRendererEvent,data:Parameters<typeof callback>[0])=>callback(data);ipcRenderer.on('workspace:capabilities',listener);return()=>ipcRenderer.removeListener('workspace:capabilities',listener);},
  onTerminal:callback => {const listener = (_event:Electron.IpcRendererEvent,data:Parameters<typeof callback>[0]) => callback(data);ipcRenderer.on('terminal:data',listener);return () => ipcRenderer.removeListener('terminal:data',listener);}
};
contextBridge.exposeInMainWorld('desktop',api);
