/** Continuation copies reviewed, visible text into an unsent draft of a new session. */
export interface SessionContinuationInput {
  sourceSessionId: string;
  snapshotHash: string;
  messageIds: string[];
  /** Optional user-written summary; never generated by a background model request. */
  summary?: string;
}
export interface SessionContinuationMessage {
  id: string;
  role: 'user' | 'assistant';
  text: string;
}
export interface SessionContinuationPreview {
  sourceSessionId: string;
  sourceProviderId: string;
  projectId: string;
  snapshotHash: string;
  messages: SessionContinuationMessage[];
  incomplete: boolean;
}
export const CONTINUATION_MESSAGE_LIMIT = 40;
export const CONTINUATION_MESSAGE_BYTES = 8 * 1024;
export const CONTINUATION_TOTAL_BYTES = 64 * 1024;
