import type { ITheme } from '@xterm/xterm';
import { normalizeThemeId, THEME_APPEARANCE, type ThemeId } from '../shared/theme';

export { DEFAULT_THEME } from '../shared/theme';
export type { ThemeId } from '../shared/theme';

/** Semantic colors are shared by the UI contrast audit and terminal palette. */
export interface ThemeDefinition {
  id: ThemeId;
  name: string;
  description: string;
  scheme: 'light' | 'dark';
  colors: Readonly<Record<string, string>>;
  terminal: Readonly<ITheme>;
}

const palettes = [
  {
    "id": "forest",
    "name": "森野绿",
    "description": "墨绿底色与薄荷高光，安静专注。",
    "scheme": "dark",
    "colors": {
      "background": "#111515",
      "sidebar": "#181e1b",
      "panel": "#161d18",
      "surface": "#1d2921",
      "elevated": "#202c24",
      "input-bg": "#121a15",
      "code-bg": "#0d1510",
      "code-header": "#203127",
      "inline-code-bg": "#293d30",
      "hover": "#293a2e",
      "selected": "#2e4535",
      "selected-border": "#91b69d",
      "user-bg": "#1d3024",
      "user-border": "#65816d",
      "text": "#e0eae3",
      "text-strong": "#f3faf5",
      "text-secondary": "#c7d8cc",
      "text-muted": "#aebfb3",
      "accent": "#b9ebcf",
      "accent-hover": "#cff5dd",
      "on-accent": "#17281d",
      "border": "#354b3b",
      "control-border": "#859b8c",
      "focus": "#c5f4d8",
      "scrollbar": "#819b89",
      "scrollbar-hover": "#a4c2ae",
      "overlay": "#030905bd",
      "shadow": "#00000066",
      "success": "#abe1b7",
      "success-bg": "#203d2a",
      "success-border": "#789f7f",
      "warning": "#eed49b",
      "warning-bg": "#392f1c",
      "warning-border": "#b69b65",
      "danger": "#ffb5aa",
      "danger-bg": "#422b29",
      "danger-border": "#bb8279",
      "info": "#a9d9ed",
      "info-bg": "#203642",
      "info-border": "#789faf",
      "syntax-keyword": "#dfb4ef",
      "syntax-string": "#b8e5aa",
      "syntax-number": "#f0ce9e",
      "syntax-comment": "#a9bab0",
      "syntax-title": "#a8d6f0",
      "diff-added-bg": "#203d2a",
      "diff-added-text": "#abe1b7",
      "diff-removed-bg": "#422b29",
      "diff-removed-text": "#ffb5aa",
      "diff-hunk-bg": "#203642",
      "diff-hunk-text": "#a9d9ed",
      "selection-bg": "#2e4535",
      "selection-text": "#f3faf5"
    },
    "terminal": {
      "background": "#111515",
      "foreground": "#e0eae3",
      "cursor": "#b9ebcf",
      "cursorAccent": "#17281d",
      "selectionBackground": "#2e4535",
      "selectionForeground": "#f3faf5",
      "black": "#91a398",
      "red": "#f5afa7",
      "green": "#b0dfb6",
      "yellow": "#e8ce95",
      "blue": "#a5c7ed",
      "magenta": "#d4b4e5",
      "cyan": "#9fd9d3",
      "white": "#dce9e1",
      "brightBlack": "#b0bfb5",
      "brightRed": "#ffc2bb",
      "brightGreen": "#c5f0c9",
      "brightYellow": "#f8dfa9",
      "brightBlue": "#bfdcff",
      "brightMagenta": "#e5c6f5",
      "brightCyan": "#b9eeea",
      "brightWhite": "#f6fcf8"
    }
  },
  {
    "id": "cloud",
    "name": "云白靛",
    "description": "冷白与雾蓝分层，靛蓝突出操作。",
    "scheme": "light",
    "colors": {
      "background": "#f7f9fe",
      "sidebar": "#eaf0fa",
      "panel": "#eef3fc",
      "surface": "#ffffff",
      "elevated": "#ffffff",
      "input-bg": "#ffffff",
      "code-bg": "#edf2fb",
      "code-header": "#dfe7f5",
      "inline-code-bg": "#e1e8f6",
      "hover": "#dce5f6",
      "selected": "#d7e2fa",
      "selected-border": "#536dab",
      "user-bg": "#e8eefc",
      "user-border": "#8b9bc1",
      "text": "#26334c",
      "text-strong": "#182541",
      "text-secondary": "#3f4e69",
      "text-muted": "#536079",
      "accent": "#344da9",
      "accent-hover": "#293d8c",
      "on-accent": "#ffffff",
      "border": "#c1cde1",
      "control-border": "#71809b",
      "focus": "#2948b0",
      "scrollbar": "#7a8aa5",
      "scrollbar-hover": "#576985",
      "overlay": "#1b294466",
      "shadow": "#15284b26",
      "success": "#23613f",
      "success-bg": "#e1f1e7",
      "success-border": "#669679",
      "warning": "#795008",
      "warning-bg": "#fff0cd",
      "warning-border": "#a18245",
      "danger": "#a12e39",
      "danger-bg": "#fce5e8",
      "danger-border": "#b7747c",
      "info": "#205d8b",
      "info-bg": "#e1f0fb",
      "info-border": "#6a92b2",
      "syntax-keyword": "#723a96",
      "syntax-string": "#256139",
      "syntax-number": "#88531c",
      "syntax-comment": "#57647c",
      "syntax-title": "#245d93",
      "diff-added-bg": "#e1f1e7",
      "diff-added-text": "#23613f",
      "diff-removed-bg": "#fce5e8",
      "diff-removed-text": "#a12e39",
      "diff-hunk-bg": "#e1f0fb",
      "diff-hunk-text": "#205d8b",
      "selection-bg": "#d7e2fa",
      "selection-text": "#182541"
    },
    "terminal": {
      "background": "#f7f9fe",
      "foreground": "#26334c",
      "cursor": "#344da9",
      "cursorAccent": "#ffffff",
      "selectionBackground": "#d7e2fa",
      "selectionForeground": "#182541",
      "black": "#26334c",
      "red": "#a02f3d",
      "green": "#276342",
      "yellow": "#76530b",
      "blue": "#315db0",
      "magenta": "#854592",
      "cyan": "#166769",
      "white": "#4f5b70",
      "brightBlack": "#59667f",
      "brightRed": "#b63043",
      "brightGreen": "#23714a",
      "brightYellow": "#815a04",
      "brightBlue": "#1f51ae",
      "brightMagenta": "#863d9c",
      "brightCyan": "#056870",
      "brightWhite": "#1c2d49"
    }
  },
  {
    "id": "sand",
    "name": "暖砂陶",
    "description": "奶油纸面与陶土红，温暖自然。",
    "scheme": "light",
    "colors": {
      "background": "#fbf5eb",
      "sidebar": "#eee2d1",
      "panel": "#f4eadb",
      "surface": "#fffaf2",
      "elevated": "#fffcf7",
      "input-bg": "#fffaf2",
      "code-bg": "#f3e8d8",
      "code-header": "#e7d8c2",
      "inline-code-bg": "#eee0cc",
      "hover": "#eaddc8",
      "selected": "#e8d4bd",
      "selected-border": "#9a6f50",
      "user-bg": "#f3e3d0",
      "user-border": "#af8c6e",
      "text": "#433326",
      "text-strong": "#322419",
      "text-secondary": "#5c4737",
      "text-muted": "#6d5846",
      "accent": "#934320",
      "accent-hover": "#783718",
      "on-accent": "#fffaf3",
      "border": "#ceb99c",
      "control-border": "#8d7358",
      "focus": "#8a3c1c",
      "scrollbar": "#917757",
      "scrollbar-hover": "#765d43",
      "overlay": "#38241366",
      "shadow": "#4a2a1429",
      "success": "#34602d",
      "success-bg": "#e7efdb",
      "success-border": "#729262",
      "warning": "#80500d",
      "warning-bg": "#fbecc5",
      "warning-border": "#a27f3a",
      "danger": "#a12f29",
      "danger-bg": "#f9dfd8",
      "danger-border": "#b57062",
      "info": "#2b5d79",
      "info-bg": "#e3edf2",
      "info-border": "#7195a5",
      "syntax-keyword": "#813e6b",
      "syntax-string": "#3f642b",
      "syntax-number": "#885006",
      "syntax-comment": "#786046",
      "syntax-title": "#2d6178",
      "diff-added-bg": "#e7efdb",
      "diff-added-text": "#34602d",
      "diff-removed-bg": "#f9dfd8",
      "diff-removed-text": "#a12f29",
      "diff-hunk-bg": "#e3edf2",
      "diff-hunk-text": "#2b5d79",
      "selection-bg": "#e8d4bd",
      "selection-text": "#322419"
    },
    "terminal": {
      "background": "#fbf5eb",
      "foreground": "#433326",
      "cursor": "#934320",
      "cursorAccent": "#fffaf3",
      "selectionBackground": "#e8d4bd",
      "selectionForeground": "#322419",
      "black": "#49372a",
      "red": "#a33830",
      "green": "#40632e",
      "yellow": "#7a550a",
      "blue": "#376080",
      "magenta": "#854d79",
      "cyan": "#286565",
      "white": "#66533f",
      "brightBlack": "#786148",
      "brightRed": "#b1352d",
      "brightGreen": "#376933",
      "brightYellow": "#815505",
      "brightBlue": "#285d87",
      "brightMagenta": "#8b3c76",
      "brightCyan": "#1b6861",
      "brightWhite": "#35291f"
    }
  },
  {
    "id": "midnight",
    "name": "极夜蓝",
    "description": "深海藏蓝与冰青光，清晰利落。",
    "scheme": "dark",
    "colors": {
      "background": "#091421",
      "sidebar": "#0d1e32",
      "panel": "#0d1c2d",
      "surface": "#12273d",
      "elevated": "#152d45",
      "input-bg": "#081827",
      "code-bg": "#07121e",
      "code-header": "#142d45",
      "inline-code-bg": "#1c3852",
      "hover": "#1b3851",
      "selected": "#1b3d58",
      "selected-border": "#70a7c5",
      "user-bg": "#102d46",
      "user-border": "#4a799b",
      "text": "#e0ebf8",
      "text-strong": "#f2f8ff",
      "text-secondary": "#c5d8eb",
      "text-muted": "#b1c5db",
      "accent": "#80d9f5",
      "accent-hover": "#a5e8fb",
      "on-accent": "#072233",
      "border": "#2d4b66",
      "control-border": "#789ab8",
      "focus": "#9be8ff",
      "scrollbar": "#799bb7",
      "scrollbar-hover": "#a3c5df",
      "overlay": "#020815c7",
      "shadow": "#0008177a",
      "success": "#9fe0bd",
      "success-bg": "#123c35",
      "success-border": "#6aa58e",
      "warning": "#f5d19a",
      "warning-bg": "#3b3020",
      "warning-border": "#b49a6c",
      "danger": "#ffb5b5",
      "danger-bg": "#442b38",
      "danger-border": "#b78090",
      "info": "#a2d7ff",
      "info-bg": "#123852",
      "info-border": "#6d9dc0",
      "syntax-keyword": "#ddb8ff",
      "syntax-string": "#a6e0bc",
      "syntax-number": "#f4ca9e",
      "syntax-comment": "#a6bdd4",
      "syntax-title": "#9ad8fc",
      "diff-added-bg": "#123c35",
      "diff-added-text": "#9fe0bd",
      "diff-removed-bg": "#442b38",
      "diff-removed-text": "#ffb5b5",
      "diff-hunk-bg": "#123852",
      "diff-hunk-text": "#a2d7ff",
      "selection-bg": "#1b3d58",
      "selection-text": "#f2f8ff"
    },
    "terminal": {
      "background": "#091421",
      "foreground": "#e0ebf8",
      "cursor": "#80d9f5",
      "cursorAccent": "#072233",
      "selectionBackground": "#1b3d58",
      "selectionForeground": "#f2f8ff",
      "black": "#8eaac3",
      "red": "#ffafbe",
      "green": "#9ce0b9",
      "yellow": "#efd095",
      "blue": "#a4c8ff",
      "magenta": "#d7b5ff",
      "cyan": "#8fdde7",
      "white": "#d8e8f7",
      "brightBlack": "#acc3d9",
      "brightRed": "#ffc4ce",
      "brightGreen": "#b9f2d0",
      "brightYellow": "#ffe2ae",
      "brightBlue": "#c1dbff",
      "brightMagenta": "#e8ceff",
      "brightCyan": "#b5f1f5",
      "brightWhite": "#f4f9ff"
    }
  },
  {
    "id": "amber",
    "name": "墨黑琥珀",
    "description": "中性炭黑与琥珀金，沉稳醒目。",
    "scheme": "dark",
    "colors": {
      "background": "#161513",
      "sidebar": "#1e1c19",
      "panel": "#1b1916",
      "surface": "#27231e",
      "elevated": "#2d2720",
      "input-bg": "#161410",
      "code-bg": "#11100e",
      "code-header": "#302a21",
      "inline-code-bg": "#3b3123",
      "hover": "#383024",
      "selected": "#473a25",
      "selected-border": "#bf9859",
      "user-bg": "#302718",
      "user-border": "#8b744e",
      "text": "#eee7dc",
      "text-strong": "#fff9ef",
      "text-secondary": "#dfd1bc",
      "text-muted": "#c5b8a3",
      "accent": "#edbd69",
      "accent-hover": "#f7d293",
      "on-accent": "#261a07",
      "border": "#514535",
      "control-border": "#a18c6d",
      "focus": "#f5cc85",
      "scrollbar": "#a18b69",
      "scrollbar-hover": "#c8ad82",
      "overlay": "#100c06c2",
      "shadow": "#00000070",
      "success": "#b9dca4",
      "success-bg": "#2d3a24",
      "success-border": "#8caa72",
      "warning": "#f3d08b",
      "warning-bg": "#40321b",
      "warning-border": "#bea16c",
      "danger": "#ffb6a1",
      "danger-bg": "#462e27",
      "danger-border": "#c18c78",
      "info": "#b1d6ef",
      "info-bg": "#263744",
      "info-border": "#85a6bd",
      "syntax-keyword": "#ddc0ec",
      "syntax-string": "#c4dba9",
      "syntax-number": "#f1ca87",
      "syntax-comment": "#bfae96",
      "syntax-title": "#acd6ed",
      "diff-added-bg": "#2d3a24",
      "diff-added-text": "#b9dca4",
      "diff-removed-bg": "#462e27",
      "diff-removed-text": "#ffb6a1",
      "diff-hunk-bg": "#263744",
      "diff-hunk-text": "#b1d6ef",
      "selection-bg": "#473a25",
      "selection-text": "#fff9ef"
    },
    "terminal": {
      "background": "#161513",
      "foreground": "#eee7dc",
      "cursor": "#edbd69",
      "cursorAccent": "#261a07",
      "selectionBackground": "#473a25",
      "selectionForeground": "#fff9ef",
      "black": "#ab9980",
      "red": "#f7b09b",
      "green": "#bfd995",
      "yellow": "#eed18c",
      "blue": "#b2cbea",
      "magenta": "#d9b9e2",
      "cyan": "#acd8d2",
      "white": "#e4d8c5",
      "brightBlack": "#c4b39b",
      "brightRed": "#ffc7b7",
      "brightGreen": "#d6ecad",
      "brightYellow": "#ffe4aa",
      "brightBlue": "#ccdef8",
      "brightMagenta": "#ead0f0",
      "brightCyan": "#c7eee8",
      "brightWhite": "#fff9ef"
    }
  }
] satisfies readonly ThemeDefinition[];

export const THEMES: readonly ThemeDefinition[] = palettes.map(theme => ({
  ...theme,
  scheme: THEME_APPEARANCE[theme.id].scheme,
  colors: { ...theme.colors, background: THEME_APPEARANCE[theme.id].background },
  terminal: { ...theme.terminal, background: THEME_APPEARANCE[theme.id].background },
}));

export function getTheme(id: unknown): ThemeDefinition {
  return THEMES.find(theme => theme.id === normalizeThemeId(id)) ?? THEMES[0];
}

export function applyTheme(id: unknown): ThemeId {
  const theme = getTheme(id);
  document.documentElement.dataset.theme = theme.id;
  document.documentElement.style.colorScheme = theme.scheme;
  return theme.id;
}

/** Return a fresh palette so xterm cannot mutate the shared theme definition. */
export function getTerminalTheme(id: ThemeId): ITheme {
  return { ...getTheme(id).terminal };
}
