import { useCallback, useEffect, useRef, useState } from 'react';
import { Check, ChevronRight, Loader2, Play, RefreshCw, Square } from 'lucide-react';
import type { Session } from '../shared/types';
import type { WorkflowRun } from '../shared/workflows';
import { MessageText } from './ChatPane';

const labels:Record<string,string>={draft:'待开始',running:'执行中',paused:'等待继续',completed:'已完成',failed:'失败',cancelled:'已取消',interrupted:'已中断',pending:'待执行'};
export function WorkflowPanel({session,onError,onTemplate}:{session:Session;onError:(error:unknown)=>void;onTemplate:(value:string)=>void}) {
  const [runs,setRuns]=useState<WorkflowRun[]>([]),[goal,setGoal]=useState(''),[pause,setPause]=useState(true),[attempts,setAttempts]=useState(2),[busy,setBusy]=useState(false),[editing,setEditing]=useState(''),[instruction,setInstruction]=useState('');
  const seq=useRef(0);
  const load=useCallback(async()=>{const request=++seq.current;const value=await window.desktop.workflows(session.id);if(request===seq.current)setRuns(value);},[session.id]);
  useEffect(()=>{void load().catch(onError);const off=window.desktop.onWorkflows(()=>void load().catch(onError));return()=>{seq.current++;off();};},[load,onError]);
  const act=async(action:()=>Promise<unknown>)=>{setBusy(true);try{await action();await load();}catch(error){onError(error);}finally{setBusy(false);}};
  return <div className="panel-content"><div className="panel-heading"><strong>阶段工作流</strong><button className="icon-button" title="刷新工作流" onClick={()=>void load().catch(onError)}><RefreshCw size={14}/></button></div>
    {session.adapter!=='structured'?<><p className="panel-note">自动阶段执行需要结构化会话。终端会话可以使用以下提示词。</p><button className="secondary compact full" onClick={()=>onTemplate('请完成以下任务：\n\n【填写目标】\n\n按规划、实现、验证三个阶段执行；阅读项目规范，检查当前改动，完成实现并运行相关测试，最后报告结果与剩余问题。')}>添加完整开发提示词</button></>:<form className="workflow-create" onSubmit={event=>{event.preventDefault();void act(async()=>{await window.desktop.createWorkflow({sessionId:session.id,goal,pauseAfterEachStage:pause,maxAttempts:attempts});setGoal('');});}}><textarea aria-label="工作流目标" placeholder="这次工作要交付什么？" value={goal} onChange={e=>setGoal(e.target.value)} maxLength={20000}/><label className="inline-checkbox"><input type="checkbox" checked={pause} onChange={e=>setPause(e.target.checked)}/>每阶段结束后由我确认继续</label><label>每阶段最多尝试<select aria-label="最大尝试次数" value={attempts} onChange={e=>setAttempts(Number(e.target.value))}><option value={1}>1 次</option><option value={2}>2 次</option><option value={3}>3 次</option></select></label><button className="primary compact full" disabled={busy||!goal.trim()||session.archived}>创建工作流</button><p className="panel-note">规划 → 实现 → 审阅。各阶段继承当前会话权限，规划指令不会强制只读；完成表示该轮执行成功，仍需审阅产出。失败后由你发起重试。</p></form>}
    {runs.map(run=><section className="workflow-run" key={run.id}><header><strong>{run.title}</strong><span className={'status-tag '+(run.status==='running'?'running':'')}>{labels[run.status]??run.status}</span></header><p className="workflow-goal">{run.goal}</p>{run.error&&<p className="chat-error">{run.error}</p>}<div className="workflow-stages">{run.stages.map((stage,index)=><div className={'workflow-stage '+stage.status} key={stage.id}><div className="stage-number">{stage.status==='completed'?<Check size={12}/>:stage.status==='running'?<Loader2 size={12} className="spin"/>:index+1}</div><div><strong>{stage.title}</strong><small>{labels[stage.status]} · {stage.attempts} / {stage.maxAttempts} 次</small>{stage.error&&<p className="chat-error">{stage.error}</p>}{stage.artifacts.map(artifact=><details key={artifact.id}><summary>{artifact.title}</summary><MessageText text={artifact.content}/></details>)}{editing===run.id+stage.id?<div><textarea aria-label="阶段指令" value={instruction} onChange={e=>setInstruction(e.target.value)}/><button className="secondary compact" onClick={()=>setEditing('')}>取消</button><button className="primary compact" disabled={busy||!instruction.trim()} onClick={()=>void act(async()=>{await window.desktop.reviseWorkflowStage(run.id,stage.id,instruction);setEditing('');})}>保存指令</button></div>:stage.status!=='running'&&stage.status!=='completed'&&!['running','cancelled','completed'].includes(run.status)&&<button className="text-button" onClick={()=>{setEditing(run.id+stage.id);setInstruction(stage.instruction);}}>编辑阶段指令</button>}</div></div>)}</div><p className="panel-note">{run.stages.some(stage=>['failed','interrupted'].includes(stage.status)&&stage.attempts>=stage.maxAttempts)?'执行次数已用完，请检查结果后新建工作流。':''}</p><div className="panel-actions">{run.status==='draft'&&<button className="primary compact" disabled={busy} onClick={()=>void act(()=>window.desktop.startWorkflow(run.id))}><Play size={12}/>开始</button>}{['paused','interrupted'].includes(run.status)&&<button className="primary compact" disabled={busy||run.stages.some(stage=>stage.status==='interrupted'&&stage.attempts>=stage.maxAttempts)} onClick={()=>void act(()=>window.desktop.continueWorkflow(run.id))}><ChevronRight size={12}/>继续</button>}{run.status==='failed'&&<button className="secondary compact" disabled={busy||run.stages.some(stage=>stage.status==='failed'&&stage.attempts>=stage.maxAttempts)} onClick={()=>void act(()=>window.desktop.retryWorkflow(run.id))}><RefreshCw size={12}/>重试失败阶段</button>}{!['completed','cancelled'].includes(run.status)&&<button className="secondary compact" disabled={busy} onClick={()=>void act(()=>window.desktop.cancelWorkflow(run.id))}><Square size={11}/>取消工作流</button>}</div></section>)}
  </div>;
}
